// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wtsfxmcsagjrzjawanlp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind0c2Z4bWNzYWdqcnpqYXdhbmxwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4MTUwMjEsImV4cCI6MjA2MzM5MTAyMX0.U2LEKgrAo0YVfjcWj4wAFbH_y6UMqtq0ISh8vuWEh9Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);